### ISSUE TITLE
[Javadoc] bintrayUpload Errors: Cannot find symbol

### ISSUE THREAD

**Issue by ThanosFisherman** [StefMa/bintray-release#10]
Hi,

Whey I try to upload my Android lib to bintray using your plugin I get several warnings and errors coming from the `androidx.annotation:annotation:1.0.0` dependency which I am using in my lib.

for example:

```
error: cannot find symbol
import androidx.annotation.NonNull;
                          ^
  symbol:   class NonNull
  location: package androidx.annotation

javadoc: warning - Class NonNull not found.
javadoc: warning - Class NonNull not found.
```

I also used to get the above messages using the pure gradle-bintray-plugin.  The library is uploaded just fine either way though.

Do you know why this is happening?

**Comment by StefMa** [comment]
Hey @ThanosFisherman 

do I understand you correctly that the warnings and errors are printed out but the gradle task run fine?

> Do you know why this is happening?

Yeah maybe.
This have something to do with the generated javadoc.
Probably it needs some addional information about theses classes.
But at the time of writing I don't know which one 😃
This will not fail the Gradle task (and upload successfully) because I added this:
[`JavaDoc.isFailOnError = false`](https://github.com/StefMa/AndroidArtifacts/blob/72a715116030baf0fd273fbf726ffa517eb31573/src/main/kotlin/guru/stefma/androidartifacts/TaskContainer.kt#L105)

**Comment by ThanosFisherman** [comment]
> do I understand you correctly that the warnings and errors are printed out but the gradle task run fine?

Yes exactly.

> This will not fail the Gradle task (and upload successfully) because I added this:
JavaDoc.isFailOnError = false

So I can just ignore the error messages? Btw The annotations library is already included in the generated pom.xml in bintray so I can't really tell what's wrong. Everything completes successfully. It's just those messages that bother me.

![46488970-deec7000-c80c-11e8-8d2c-391e4ca5c032](https://user-images.githubusercontent.com/4888330/46559776-040adc80-c8fa-11e8-9a40-5624cf6e0009.png)

**Comment by StefMa** [comment]
> So I can just ignore the error messages?

Yes, you can.
For now 🙃 
The javadoc is not generated correctly.. for whatever reasons.
So your library users don't see the javadoc correctly.

You can check that out to go into:
```
LOCAL_MAVEN/your/group/artifactId/NAME-javadoc.jar
```
rename the *jar to *zip.
Extract them and open the index.html.

It may happen that they don't contain the NonNull/Nullable annotation...

**Comment by StefMa** [comment]
Oh and btw.
I thought I have already fixed that int he upstream plugin https://github.com/StefMa/AndroidArtifacts.

I'll  hopefully - update this plugin soon.
It would be great if you can test it than again and report if its working 👍

**Comment by ThanosFisherman** [comment]
Thank you for your help. Indeed the index.html is missing NonNull/Nullable annotations

Regarding your other plugin AndroidArtifacts I tried it today but can't seem to make it build as I am getting the following error

```
Could not find method license() for arguments [build_k5p3wiayon3nop252ngk666d$_run_closure3$_closure9@306aa8a3] on object of type guru.stefma.androidartifacts.ArtifactsExtension.
```
When I remove the whole license closure it builds fine tho. Maybe I am missing something. I'll try again later.

**Comment by StefMa** [comment]
The new version which contains the `license` method is not published in a stable version yet.
You have to use the **SNAPSHOT** version to test these feature..

**Comment by StefMa** [comment]
Hey @ThanosFisherman 

could you pls test the latest SNAPSHOT version and take a look if it fix the javadoc issue?
(You can also use the `license()` method then 😉):

This is how to do it:
```groovy
buildscript {
    repositories {
        jcenter()
        google()
        maven { url "https://jitpack.io" }
    }
    dependencies {
        classpath "com.github.stefma:bintray-release:master-SNAPSHOT"
    }
}

// Your other plugins
apply plugin: "guru.stefma.bintrayrelease"

version = "1.0.0"
group = "guru.stefma.bintrayrelease"
androidArtifact { 
    artifactId = "YOUR-ARTIFACT-NAME"
    license {
        // Your license setup
    }
}
publish {
    userOrg = 'YOUR_USERORG'
    // Other stuff which needs to be set up
}
```

Thank you :)

**Comment by ThanosFisherman** [comment]
Hey @StefMa 

Yes I will test it later this day and let you know.

Cheers

**Comment by ThanosFisherman** [comment]
Hi @StefMa ,

I just tried it and it seems to be building successfully no javadoc errors.

However I don't quite understand. What am I supposed to do now? My Android Library is only published on bintray not on maven central. And from what I can tell the plugin didn't publish anything on bintray.

**Comment by StefMa** [comment]
> I just tried it and it seems to be building successfully no javadoc errors.

cool 🎉 Thanks for testing 👍 

> However I don't quite understand. What am I supposed to do now? My Android Library is only published on bintray not on maven central. And from what I can tell the plugin didn't publish anything on bintray.

Of course, it does 🙃 
*this* Plugin (bintray-release) will publish your library to bintray. That have nothing to do with maven central.

**Comment by StefMa** [comment]
Yesterday I published the version [1.1.0 to jcenter](https://github.com/StefMa/bintray-release/releases/tag/v1.1.0).
Feel free to use the stable version to publish your lib 👍

**Comment by ThanosFisherman** [comment]
Cool thanks for the clarification. I'll give it a try as soon as my next release is ready. 🙃

**Comment by StefMa** [comment]
I'll close this for now.
Feel free to open another issue when you facing the same/another issue then 👍
