### ISSUE TITLE
Dependence Error

### ISSUE THREAD

**Issue by yhyzgn** [StefMa/bintray-release#13]
I have uploaded library successful,  but some error happened when sync dependence : 
      " Failed to resolve: null:unspecified:null "

**Comment by StefMa** [comment]
Could you please show me all of your declared dependencies?

**Comment by yhyzgn** [comment]
These are my dependencies :
```
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    androidTestImplementation('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    implementation 'com.yhy.widget:view-core:1.3.15'
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support:recyclerview-v7:27.1.1'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    //noinspection GradleDependency
    implementation 'com.github.bumptech.glide:glide:3.6.1'
    // Picasso
    implementation 'com.squareup.picasso:picasso:2.5.2'
    implementation 'com.squareup.picasso:picasso:2.5.2'
    testImplementation 'junit:junit:4.12'
}
```

**Comment by StefMa** [comment]
> implementation fileTree(dir: 'libs', include: ['*.jar'])

That is the issue.
Remove it and it should work as expected.

Related #4

**Comment by yhyzgn** [comment]
Sorry, it dosen't work .
And this message is showing while synchronizging .
![aa](https://user-images.githubusercontent.com/20694902/47126058-56b0a500-d2b9-11e8-983b-772129e81084.png)

**Comment by StefMa** [comment]
Sure, it works.
See the test here
https://github.com/StefMa/AndroidArtifacts/blob/7175bee0947fb1f27a0074d9fd4a9c1f123aa800/src/test/kotlin/guru/stefma/androidartifacts/plugin/AndroidArtifactsPluginTest.kt#L121-L135

The problem you are showing is that you download a dependency which has already an invalid POM file.

When you have to publish your project  again, you have to set the `-Poverride=true` property.
Otherwise it will not *override* you existing project at bintray.

You could also check your project in the local maven (on Unix systems at `~/.m2`) and take a look into the POM file there. It shouldn't contain any `null/unspecified/`dependency...

**Comment by yhyzgn** [comment]
Now, I have upgraded to version `1.1.0`, and have configured `build.gradle` as your README, the `pom` file has no problem as expected .
However, the version of library is not exist on `bintray` , but the console shows `uploading to https://api.bintray.com/xxx` and `BUILD SUCCESSFUL in 1m 37s` . 
Em ... What the hell about this ?

**Comment by StefMa** [comment]
I really need addional information how you upload your library.

By default the plugin run only in a "dryRun" mode. means it will brint that it would be upload but it *will not* upload..
Probably you have to add `-PdryRun=false`

**Comment by yhyzgn** [comment]
Em... sorry, it doesn't work either .
Here is gradle script : `gradlew clean build bintrayUpload -PbintrayUser=xxxx -PbintrayKey=xxxx -PdryRun=false -Poverride=true`, I really could not find what problem about this .
Thank you very much .

**Comment by StefMa** [comment]
Well, you probably run into [this issue](https://github.com/StefMa/bintray-release/pull/29).
The solution would be to add `dryRun = false`  to  the `publish` extension 👍
