### ISSUE TITLE
Something is wrong with v1.1.0

### ISSUE THREAD

**Issue by r17171709** [StefMa/bintray-release#28]
> How to fix it?

![cj5p8w6](https://user-images.githubusercontent.com/10229883/47217048-5c84b400-d3a7-11e8-8599-4876b2f118b7.png)

**Comment by StefMa** [comment]
😕 
I don't know 🤷‍♂️ 
Never saw this error before.
Can you please send more details?
* Gradle Version
* Applied Plugins 
* custom publications?!

**Comment by r17171709** [comment]
> 😕
> I don't know 🤷‍♂️
> Never saw this error before.
> Can you please send more details?
> 
> * Gradle Version
> * Applied Plugins
> * custom publications?!

gradle4.8
classpath 'com.github.StefMa:bintray-release:v1.1.0'
