### ISSUE TITLE
Can you update androidartifact to version 1.4.0 and publish it

### ISSUE THREAD

**Issue by qtiuto** [StefMa/bintray-release#35]
Only several minutes.

**Comment by StefMa** [comment]
I've already a PR for that. See #34

**Comment by qtiuto** [comment]
Sorry, I don't see it before. When will you merge the branch and publish it
to github or bintray?

Stefan M. <notifications@github.com> 于2019年2月14日周四 下午2:31写道：

**Comment by StefMa** [comment]
The plan is to merge this as soon as I've fixed the test and publish i afterwards as a "maintainance" update...
I think you can expected it in a few hours...

Are there a special feature/fix from AndroidArtifacts 1.4 you like to use? 
If so - which one?

**Comment by StefMa** [comment]
Fixed. 
See https://github.com/StefMa/bintray-release/releases/tag/v1.1.2
