### ISSUE TITLE
How to change repo name from maven to custom

### ISSUE THREAD

**Issue by artivatic-data** [StefMa/bintray-release#37]
I want to change my bintray repo name from maven to custom.

**Comment by StefMa** [comment]
You can define the `repo` inside the `publish` block:
```
publish {
  repo = "yourRepoName"
}
```

See also [this class](https://github.com/StefMa/bintray-release/blob/9e8633eea825fcc38c912da2adb56c501a5293b7/src/main/kotlin/guru/stefma/bintrayrelease/PublishExtension.kt) for all possible options.
