### ISSUE TITLE
Error during gradle sync: "Cannot configure the 'publishing' extension after it has been accessed."

### ISSUE THREAD

**Issue by prasannajeet** [StefMa/bintray-release#8]
I use a `publishing` tag in my module/build.gradle because I use mavenLocal() for testing my internal library releases. 

I used to use the novoda plugin and had no issues. But due to gradle 4.6 issues with novoda plugin I have switched to this fork and now I can't gradle sync my project.

My publishing tag looks like below

![image](https://user-images.githubusercontent.com/3320483/45982412-4e4cad80-c01e-11e8-8d92-11bfa40bfc67.png)

[Code Snippet](https://gitlab.com/snippets/1757019)

If I remove the publishing tag and sync, it works. But then adding the artifact from mavenLocal to any sample Android application leads to the following error:

![image](https://user-images.githubusercontent.com/3320483/45986873-ca9dbb80-c033-11e8-88be-05b1e8d0c903.png)

Apologies if this is something I am not able to understand and implement as intended. But, I am looking for a way to implement this plugin and keep my publishing tag at the same time.

**Comment by StefMa** [comment]
Hey @prasannajeet 
first of all - when you only want to publish your libs to the local maven [this plugin](https://github.com/StefMa/AndroidArtifacts) would be better fit your needs.

Anyway. It is should work with this plugin too 😄 

1. Why do you declare your own `publishing` block?
Normally this plugin take care of it. There is no need to declare it by yourself.
2. Can you please post all of your dependencies?  It seems that one of your `Dependency` isn't resolved correctly.
This might be an issue with the `AndroidArtifacts` plugin of the current release.

You could try to use the current "master-SNAPSHOT" version of *this* plugin via [JitPack](https://jitpack.io/#StefMa/bintray-release/master-SNAPSHOT).
The master should have an updated version of the `AndroidArtifacts` plugin which resolved the dependencies correctly.
Beside of "local dependencies". Thus needs to be published too - of course.

**Comment by prasannajeet** [comment]
Hi @StefMa ,

Glad to receive your quick response. 

Actually, I use both local maven publish and bintray upload in my project. The reason I declare the publishing block is to eliminate the "undefined" dependency in my pom.xml that gets generated. Using that _if_ condition cleans up my POM xml to only have valid dependencies. Even when I used the **novoda** plugin I had to keep this publishing block as the remote POM in bintray used to have the undefined dependency in its POM xml and was causing issues.

[Here is the complete build.gradle file in my module](https://gitlab.com/prasannajeet/Janus/blob/develop/janus-authenticator/build.gradle)

Using the `AndroidArtifacts `plugin is an option I can use but honestly I would rather have one plugin that works for both. And novoda plugin did that for me. I can see your plugin has definitely made things easier than novod

**Finally, I would like to appreciate you taking your valuable time to work with me on resolving this :)**

**Comment by prasannajeet** [comment]
Hi @StefMa ,

I have found a resolution for the issue. Turns out deleting the following line actually fixed the whole POM file for me.

`implementation fileTree(include: ['*.jar'], dir: 'libs')`

I will now be closing the issue. Thank you for your time.

**Comment by StefMa** [comment]
Glad that I can help with that :)

This is indeed the error.
See also #4 and https://github.com/StefMa/AndroidArtifacts/issues/39

Probably I should track this better in the "parent plugin".
Maybe by failing on an `undefinied`  dependency 🤔
