### ISSUE TITLE
Add <licenses> tag in POM file for AAR

### ISSUE THREAD

**Issue by prasannajeet** [StefMa/bintray-release#9]
Hi @StefMa ,

Requesting you to enable support for adding a `<licenses>` tag along with license information to be added in the generated POM file that accompanies the AAR file generated using the plugin.

**Necessity for change?**

I noticed this issue when I was using my [library ](https://bintray.com/prasannajeet89/praszappsMaven/janus/0.4.8#files/com%2Fpraszapps%2Fbiometric%2Fjanus%2F0.4.8) along with [Google's Open Source Notices API](https://developers.google.com/android/guides/opensource#how_licenses_are_determined) in an application about to go into production. This API shows an activity listing the notices of all open source dependencies used in someone's application.

[As per Google](https://developers.google.com/android/guides/opensource#how_licenses_are_determined), it looks for `<licenses>` tag inside a POM file of the artifact to make a determination of the license information and then lists it for declaration. It needs the license name and URL information for the same. If you notice the screenshot at the end, it's missing the artifact `com.praszapps.biometric:janus`

[If you see my attached file ](https://github.com/StefMa/bintray-release/files/2430991/janus-0.4.8.pom.txt), it is missing the licenses tag with the required information. 

I did observe that you are setting the [license tag by default to Apache 2.0](https://github.com/StefMa/bintray-release/blob/master/src/main/kotlin/guru/stefma/bintrayrelease/PublishExtension.kt#L43). However, even then no license tags get generated in the POM file.

**Proposed Solution**

Please provide the capability for us to specify a licenseName and licenseUrl attribute in the publish extension and enable adding the same in our POM file. It will help us deal with the legal compliance when using our libraries in production applications.

Right now our team is blocked from taking our application into production as we are not declaring the license of the library and our compliance expert is asking us to hold off until we get it listed.

**Screenshot**

![screenshot](https://user-images.githubusercontent.com/3320483/46250353-b9bbc400-c3fe-11e8-8d6b-4f4e3db53481.png)

**Comment by StefMa** [comment]
Thanks @prasannajeet for the request.
This will be fixed with [this upstream issue](https://github.com/StefMa/AndroidArtifacts/issues/37). 
I will keep this open as long as this plugin have this issue...

**Comment by StefMa** [comment]
This goes hand in hand with #12 .
When I extract the `androidArtifact {}` blcok into its own there is no need to maintain this plugin extension with updates anymore...
